### ISSUE TITLE
Options in collection method?

### ISSUE THREAD

**Issue by aendrew** [yeoman/generator-jquery#23]
Hi!
The generator scaffolds out a collection method, a static method, default options for the static method and a custom selector. In order to use the static method's default options in the collection method, I'm guessing I'd pass an options argument and then do `options = $.extend({}, $.myplugin.options, options);` like is done in the static method?

If so, this should maybe be clarified (or options passed to the collection method as they're currently done to the static method). I'm not a *total* neophyte in terms of writing jQuery plugins, but I found the scaffolded code confusing enough to stop me for a moment...

**Comment by sindresorhus** [comment]
No, let's keep the discussion here. grunt-init is effectively unmaintained and nothing will come out of discussing there.

**Comment by arthurvr** [comment]
I can work on this for sure. Will do it after https://github.com/yeoman/generator-jquery/pull/39.

**Comment by arthurvr** [comment]
> The generator scaffolds out a collection method, a static method, default options for the static method and a custom selector.

As of https://github.com/yeoman/generator-jquery/pull/39, that's not really true anymore.

**Comment by aendrew** [comment]
@arthurvr I haven't used this generator in awhile; your PR looks totally like what I was wanting though. Can I effectively close this issue then?

**Comment by arthurvr** [comment]
If I am not understanding you wrong, yup!

**Comment by aendrew** [comment]
Awesome, thanks! :smile: :shipit:
