### ISSUE TITLE
Add method types question

### ISSUE THREAD

**Issue by aendrew** [yeoman/generator-jquery#26]
Right now, due to its really basic usage of `grunt-jquery-init`, it seems `generator-jquery` doesn't fully leverage the power of Yeoman to scaffold out the desired plugin.

For instance, if all you want to build is a collection-based plugin, the static method and selector methods will be unpopulated and probably ultimately removed. In fact, if you've never coded a jQuery plugin and are looking to the generator with the intent of learning best practices, the extra methods might even be confusing.

One solution would be to add a prompt asking which scaffolds the user wants added to name.js. If this is desirable, let me know and I'll write a pull request later.

Thanks!

**Comment by sindresorhus** [comment]
:+1: PR welcome :)

**Comment by arthurvr** [comment]
Will PR this evening

**Comment by aendrew** [comment]
@arthurvr :clap:

**Comment by arthurvr** [comment]
It took longer than I said, but https://github.com/yeoman/generator-jquery/pull/39.
