### ISSUE TITLE
Can't Install Generator Properly, Always got some error.

### ISSUE THREAD

**Issue by Mantrama** [yeoman/generator-jquery#33]
Running "qunit:all" (qunit) task
Testing http://localhost:9000/test/jquery.html FFFF
>> jQuery#awesome - is chainable
>> Message: Died on test #1     at http://localhost:9000/bower_components/qunit/qunit/qunit.js:425
>>     at http://localhost:9000/test/jquery_test.js:34
>>     at http://localhost:9000/test/jquery_test.js:62: 'undefined' is not a function (evaluating 'this.elems.awesome()')
>> TypeError: 'undefined' is not a function (evaluating 'this.elems.awesome()')

>> jQuery#awesome - is awesome
>> Message: Died on test #1     at http://localhost:9000/bower_components/qunit/qunit/qunit.js:425
>>     at http://localhost:9000/test/jquery_test.js:39
>>     at http://localhost:9000/test/jquery_test.js:62: 'undefined' is not a function (evaluating 'this.elems.awesome()')
>> TypeError: 'undefined' is not a function (evaluating 'this.elems.awesome()')

>> jQuery.awesome - is awesome
>> Message: Died on test #1     at http://localhost:9000/bower_components/qunit/qunit/qunit.js:425
>>     at http://localhost:9000/test/jquery_test.js:47
>>     at http://localhost:9000/test/jquery_test.js:62: 'undefined' is not a function (evaluating '$.awesome()')
>> TypeError: 'undefined' is not a function (evaluating '$.awesome()')

>> jQuery.awesome - is awesome
>> Message: Expected 2 assertions, but 1 were run
>> at http://localhost:9000/bower_components/qunit/qunit/qunit.js:425
>>   at http://localhost:9000/test/jquery_test.js:47
>>   at http://localhost:9000/test/jquery_test.js:62

>> :awesome selector - is awesome
>> Message: Died on test #1     at http://localhost:9000/bower_components/qunit/qunit/qunit.js:425
>>     at http://localhost:9000/test/jquery_test.js:60
>>     at http://localhost:9000/test/jquery_test.js:62: Syntax error, unrecognized expression: unsupported pseudo: awesome
>> Error: Syntax error, unrecognized expression: unsupported pseudo: awesome

Warning: 5/5 assertions failed (243ms) Use --force to continue.

Aborted due to warnings.

**Comment by sindresorhus** [comment]
Fixed in 1.0.0.
