### ISSUE TITLE
get rid of references to plugins registry

### ISSUE THREAD

**Issue by arthurvr** [yeoman/generator-jquery#35]
In the [`welcome` message](https://github.com/yeoman/generator-jquery/blob/master/app/index.js#L14) we're making multiple references to the jQuery plugins registry and publishing plugins in there. That doesn't really make sense anymore, since the plugins site is currently in ["read-only mode"](http://plugins.jquery.com/).

**Comment by sindresorhus** [comment]
:+1: Wanna do a PR?

**Comment by arthurvr** [comment]
Sorry, @sindresorhus, missed your comment. Will do PR this evening ;)

**Comment by arthurvr** [comment]
@sindresorhus https://github.com/yeoman/generator-jquery/pull/37
