### ISSUE TITLE
`yo jquery` error.

### ISSUE THREAD

**Issue by Mystist** [yeoman/generator-jquery#36]
Generator version: 1.1.0
I'm using proxy.

Run `yo jquery`, always press ENTER, got an `undefined` before the welcome message:
``` javascript
undefined"Project Name" should not contain "jquery" or "js" and should be a unique ID not already in use at plugins.jquery.com. "Project title" should be a human-readable title, and doesn't need to contain the word "jQuery", although it may. For example, a plugin titled "Awesome Plugin" might have the name "awesome-plugin".
```

Then got the ERROR:
``` javascript
/usr/local/lib/node_modules/generator-jquery/app/index.js:47
          if (!available.npm || !available.bower) {
                        ^
TypeError: Cannot read property 'npm' of undefined
    at /usr/local/lib/node_modules/generator-jquery/app/index.js:47:25
    at /usr/local/lib/node_modules/generator-jquery/node_modules/pkg-name/index.js:25:4
    at callback (/usr/local/lib/node_modules/generator-jquery/node_modules/pkg-name/node_modules/each-async/index.js:33:4)
```

After canceled the proxy, the ERROR gone, but `this.yeoman` still got `undefined`, before the welcome message.

**Comment by Mystist** [comment]
Why behind proxy doesn't work, I've set proxy from bash and npm.

**Comment by arthurvr** [comment]
> Run yo jquery, always press ENTER, got an undefined before the welcome message:

That will be fixed together with https://github.com/yeoman/generator-jquery/pull/37.

**Comment by arthurvr** [comment]
Can somebody close this? The PR removing it was merged.

**Comment by arthurvr** [comment]
@Mystist @kevva ^ one of you who wants to close this? Thx
