### ISSUE TITLE
Test plugin against multiple jQuery versions?

### ISSUE THREAD

**Issue by sergzbx** [yeoman/generator-jquery#45]
_(my first contribution to open source, hope I'm doing everything right. Sorry if I don't!)_

When testing my plugin using the basic QUnit testcase I get, I feel like I'm not really testing well. My plugin is only getting tested against the jQuery version I gave up although it should test on every supported version. For example if I say my plugin supports 1.9 and later, I want it to be tested on:

* 1.9 and all its patch releases
* 1.10 and all its patch releases
* 1.11 and all its patch releases
* 2 and all its patch releases
* 2.1 and all its patch releases
* jQuery 3.0 via the git cdn they have, so I'm sure my plugin doesn't break when they release.
* jQuery 3.0 compat via the git cdn they have, so I'm sure my plugin doesn't break when they release.

I know that jQuery UI and jQuery Mobile have CI setup to test this, but I have not dug into how they do that. Sorry therefor but I'm not that of a grunt pro.

If I'm going way too in here or am just asking for way to complicated stuff sorry. If you don't want to integrate this into the main templates, maybe consider a recipe similar to other generators? Thank you for this generator and thanks for building Yeoman.

**Comment by arthurvr** [comment]
Sounds interesting although it would complicate the setup quite a bit. Do we think it's worth it?

**Comment by addyosmani** [comment]
I wonder if this is a case where a separate generator that adds this functionality but relies on composability with `generator-jquery` would make sense.

**Comment by arthurvr** [comment]
> I wonder if this is a case where a separate generator that adds this functionality but relies on composability with generator-jquery would make sense.

I think that would make sense, yes. I personally feel like this would complicate the setup quite a bit and I wonder if it's needed for everyone. The amount of plugins that need/do this is very small.

**Comment by arthurvr** [comment]
What does the rest think?

**Comment by arthurvr** [comment]
> What does the rest think?

ping?

**Comment by arthurvr** [comment]
There was never much response to this issue, and I personally think it's overkill in most cases so I'm going to close this. But as Addy mentioned, this is perfectly possible in a generator that relies on composability.

**Comment by eddiemonge** [comment]
I agree with @sergzbx about testing against every supported version...however, that is outside the scope of this generator. It should be up to the author to implement testing strategies. So yes this should be closed.
